version: '3'

services:
  app:
    image: regangiri/sudutbarber:latest
    platform: linux/amd64
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env.production
    restart: always

  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: regan
      POSTGRES_PASSWORD: regan12345
      POSTGRES_DB: sudutbarber
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
